// Top-level build file - Official Google repositories only
buildscript {
    ext.kotlin_version = '1.9.22'
    ext.hilt_version = '2.50' // Added Hilt version

    ext {
        compileSdkVersion = 34
        targetSdkVersion = 34
        minSdkVersion = 30
        ndkVersion = "25.1.8937393"
    }

    repositories {
        // Official Google Maven Repository
        google()
        // Official Maven Central
        mavenCentral()
        // Official Gradle Plugin Portal
        gradlePluginPortal()
    }

    dependencies {
        // Official Android Gradle Plugin
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hilt_version" // Added Hilt plugin
    }
}

allprojects {
    repositories {
        // Same official repositories
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}